name: Build and Test Spring Boot App

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mydb
          MYSQL_USER: user
          MYSQL_PASSWORD: password
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      mongodb:
        image: mongo:6
        ports:
          - 27017:27017

    env:
      SPRING_APPLICATION_NAME: "cacs-application"
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_NAMING_IMPLICIT_STRATEGY: "org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl"
      SPRING_JPA_HIBERNATE_NAMING_PHYSICAL_STRATEGY: "org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl"
      MYSQL_HOST: "localhost"
      SPRING_DATA_MONGODB_HOST: "localhost"
      SPRING_DATA_MONGODB_PORT: "27017"
      SPRING_DATA_MONGODB_DATABASE: "mydb"
      SERVER_PORT: "8080"
      SPRING_DATASOURCE_URL: "jdbc:mysql://127.0.0.1:3306/mydb"
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set Up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.9.6'
    
      - name: Verify Database Connection
        run: |
          echo "Checking MySQL and MongoDB..."
          sleep 10 # Ensures containers are ready
          mysql --host=localhost --port=3306 --user=root --password=root -e "SHOW DATABASES;"
          mongo --host=localhost --port=27017 --eval "db.runCommand({ connectionStatus: 1 })"

      - name: Build with Maven
        run: mvn clean install

      - name: Run Tests
        run: mvn test -Dspring.profiles.active=test

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: target/*.jar
