name: Build and Test

on:
  pull_request:   # Triggers when a PR is opened, synchronized, or updated
    branches:
      - main  # Adjust based on your target branch
  push:   # Triggers when merging into main
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn clean install
