name: ZAP Scan on Localhost

on:
  workflow_dispatch:

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21' # Updated to Java 21

      - name: Build with Maven
        run: |
          mvn clean install
          mvn spring-boot:run &  # Start the server in the background

      - name: Wait for Application to Start
        run: sleep 30  # Adjust the wait time as needed

      - name: ZAP Full Scan
        uses: zaproxy/action-full-scan@v0.1.0
        with:
          target: 'http://localhost:8080'
          fail_action: false  # Prevent the workflow from failing immediately on findings
